name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: plugin_version
    attributes:
      label: Plugin version
      description: Which version of the plugin are you using ?
      placeholder: vX.Y.Z
    validations:
      required: true
  - type: input
    id: vscode_version
    attributes:
      label: VSCode version
      description: Which version of vscode are you using ?
      placeholder: vX.Y.Z
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Output
      description: If you received an error output that is too long, use Gists

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: List any custom configurations and the steps to reproduce this error
