# Github action for releasing the binaries
name: release

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:  

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: | 
          npm install
          npm run-script package

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          files: |
            ./osc-viewer-*.vsix